# Generated by Django 3.0.4 on 2020-03-25 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('forGrade', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='OwnedByTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksOwned', models.PositiveSmallIntegerField()),
                ('booksReturned', models.PositiveSmallIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booky.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('books', models.ManyToManyField(through='booky.OwnedByTeacher', to='booky.Book')),
            ],
        ),
        migrations.AddField(
            model_name='ownedbyteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booky.Teacher'),
        ),
        migrations.CreateModel(
            name='OwnedByClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksOwned', models.PositiveSmallIntegerField()),
                ('booksReturned', models.PositiveSmallIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booky.Book')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booky.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('isbn', models.CharField(max_length=17)),
                ('publicationYear', models.PositiveSmallIntegerField()),
                ('registryNumber', models.CharField(max_length=15)),
                ('billingNumber', models.CharField(max_length=20)),
                ('amountOrdered', models.PositiveSmallIntegerField()),
                ('pricePerBook', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dateOfArrival', models.DateTimeField()),
                ('forBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booky.Book')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='books',
            field=models.ManyToManyField(through='booky.OwnedByClass', to='booky.Book'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booky.Grade'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('books', models.ManyToManyField(to='booky.Book')),
            ],
        ),
    ]
