# Generated by Django 3.0.4 on 2020-03-25 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booky', '0002_auto_20200325_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='books',
            field=models.ManyToManyField(through='booky.OwnedByClass', to='booky.Book'),
        ),
        migrations.AlterField(
            model_name='ownedbyclass',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classOwnership', to='booky.Book'),
        ),
        migrations.AlterField(
            model_name='ownedbyclass',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='booky.Classroom'),
        ),
        migrations.AlterField(
            model_name='ownedbyteacher',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachersOwnership', to='booky.Book'),
        ),
        migrations.AlterField(
            model_name='ownedbyteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='booky.Teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='books',
            field=models.ManyToManyField(through='booky.OwnedByTeacher', to='booky.Book'),
        ),
    ]
