# Generated by Django 3.0.4 on 2020-03-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booky', '0003_auto_20200325_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='booksLost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='books',
            field=models.ManyToManyField(related_name='classrooms', through='booky.OwnedByClass', to='booky.Book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='forBook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='booky.Book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='isbn',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pricePerBook',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='registryNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ownedbyclass',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='booky.Classroom'),
        ),
        migrations.AlterField(
            model_name='ownedbyteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='booky.Teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='books',
            field=models.ManyToManyField(related_name='teachers', through='booky.OwnedByTeacher', to='booky.Book'),
        ),
    ]
