# Generated by Django 3.0.4 on 2020-03-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booky', '0004_auto_20200325_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(default='lol', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='forBook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='booky.Book'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
