# Generated by Django 3.0.4 on 2020-03-30 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booky', '0005_auto_20200327_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dateOfArrival',
        ),
        migrations.AddField(
            model_name='order',
            name='dateOrdered',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ownedbyclass',
            name='booksOwned',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ownedbyclass',
            name='booksReturned',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ownedbyteacher',
            name='booksOwned',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ownedbyteacher',
            name='booksReturned',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
