# Generated by Django 3.0.4 on 2020-03-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booky', '0006_auto_20200330_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amountOrdered',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
