# Generated by Django 3.0.4 on 2020-04-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booky', '0008_auto_20200403_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedbyclass',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classInfo', to='booky.Book'),
        ),
        migrations.AlterField(
            model_name='ownedbyclass',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookInfo', to='booky.Classroom'),
        ),
        migrations.AlterField(
            model_name='ownedbyteacher',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherInfo', to='booky.Book'),
        ),
        migrations.AlterField(
            model_name='ownedbyteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookInfo', to='booky.Teacher'),
        ),
    ]
